### ISSUE TITLE
Ensure all Kubernetes repos include a SECURITY.md

### ISSUE THREAD

**Issue by tallclair** [kubernetes/security#105]
See https://github.com/kubernetes/kubernetes-template-project/pull/35. Once that merges into the project template, we need to update all the repos to add the new file.

**Comment by nikhita** [comment]
The SECURITY.md file is now defined org-wide for all Kubernetes GitHub orgs - https://github.com/kubernetes/org/issues/2081#issuecomment-670495073. 

I guess we can keep this issue open until https://github.com/kubernetes/kubernetes/pull/93486 is merged though.

**Comment by sftim** [comment]
/remove-lifecycle stale
https://github.com/kubernetes/kubernetes/pull/93486 not yet merged
