### ISSUE TITLE
Joel Smith: Onboarding to PST

### ISSUE THREAD

**Issue by philips** [kubernetes/security#11]
- [x] Add/remove from https://github.com/kubernetes/community/blob/master/sigs.yaml#L2602
- [x] Add/remove from OpsGenie rotation
- [x] https://groups.google.com/a/kubernetes.io/forum/#!forum/security owner
- [x] https://groups.google.com/a/kubernetes.io/forum/#!forum/security owner
- [x] https://groups.google.com/forum/#!forum/kubernetes-security-discuss owner
- [x] https://groups.google.com/forum/#!forum/kubernetes-security-announce owner
- [x] https://groups.google.com/a/kubernetes.io/forum/#!forum/distributors-announce owner
- [x] https://github.com/kubernetes-security/security-disclosures/issues access
- [ ] ???

After doing this write an onboarding doc.

**Comment by joelsmith** [comment]
Do I need to be added to either of these?
https://github.com/kubernetes/community/blob/master/sigs.yaml#L2596
https://github.com/kubernetes/org/blob/master/config/kubernetes/org.yaml#L1851
(I'm not sure if one is generated from the other)

**Comment by philips** [comment]
@joelsmith yes, PR is up https://github.com/kubernetes/community/pull/3459

**Comment by tallclair** [comment]
/assign @joelsmith 

I think this is done?
