### ISSUE TITLE
offboard Jess Frazelle

### ISSUE THREAD

**Issue by philips** [kubernetes/security#16]
- [ ] Add/remove from https://github.com/kubernetes/community/blob/master/sigs.yaml#L2602
- [x] Add/remove from OpsGenie rotation
- [x] https://groups.google.com/a/kubernetes.io/forum/#!forum/security owner
- [x] https://groups.google.com/a/kubernetes.io/forum/#!forum/security-discuss-private owner
- [x] https://groups.google.com/forum/#!forum/kubernetes-security-discuss owner
- [x] https://groups.google.com/a/kubernetes.io/forum/#!forum/distributors-announce owner
- [x] https://github.com/kubernetes-security/security-disclosures/issues access
- [ ] ???

Via https://github.com/kubernetes/security/pull/15

**Comment by philips** [comment]
PR up for sigs.yaml https://github.com/kubernetes/community/pull/3482/files

**Comment by tallclair** [comment]
Anything left here?
