### ISSUE TITLE
Add Ubuntu Security to security list for Kubernetes. 

### ISSUE THREAD

**Issue by joemcmanus** [kubernetes/security#29]
**Actively monitored security email alias for our project:**
security@ubuntu.com 

**1. Be an actively maintained and CNCF certified distribution of Kubernetes components.**
Canonical distributes and supports CNCF Kubernetes systems. 

**2. Have a user base not limited to your own organization.**
Yes

**3. Have a publicly verifiable track record up to present day of fixing security issues.**
Please view usn.ubuntu.com to see the list of issues we have fixed over time. 

**4. Not be a downstream or rebuild of another distribution.**
We are not. 

**5. Be a participant and active contributor in the community.**
We are an active participant to the k8s community. 

**6. Accept the Embargo Policy.**

Yes, the security team is aware of and participates in embargoed security issues. 

**7. Be willing to contribute back.**

As a proud member of the Open Source community we would be happy to commit back. 

**8. Have someone already on the list vouch for the person requesting membership on behalf of your distribution.**
Jorge Castro should be able to vouch for us. 

Please let me know if you have any questions! -Joe

**Comment by philips** [comment]
gah, sorry for not responding to this for weeks!

This looks good to me. So, I will add you to the list.

cc @castrojo

**Comment by philips** [comment]
PR is up, and an invite to the group was sent.

https://github.com/kubernetes/security/pull/32

/close
