### ISSUE TITLE
Revisit response timelines

### ISSUE THREAD

**Issue by tallclair** [kubernetes/security#39]
Our process documentation includes a bunch of timelines that I don't think we've followed.

We should review the timelines, and update them to something we expect to follow more closely if necessary. Then, we should make an effort to hold ourselves to those timelines.

Also, we should decide how to handle vulnerabilities that are legitimate vulnerabilities, but things we aren't going to prioritize fixing (generally because they're low severity & the fix requires a lot of work).

**Comment by philips** [comment]
+1 I think our timelines are too aggressive as well.

Context: When the document was originally written we were hoping to have tighter control over the release process; but in practice trying to have that level of control leads to an extremely high amount of effort and eventual burn out. So, we should document the reality.

**Comment by tallclair** [comment]
I think we should take a user-centric approach to this, where everyone on distributors-announce are our users. I'd like to put together a questionnaire to collect feedback from distributors on how they use the embargo announcements, with details like what the ideal embargo length would be, and what their severity threshholds are for handling vulnerabilities. My hope was that the security process working group could own this.

**Comment by micahhausler** [comment]
I'd be happy to help out on getting the questionnaire out and working on this

**Comment by philips** [comment]
What is the next step on the Kube security response stuff? It has been a
couple of weeks since the last response.

**Comment by tallclair** [comment]
/remove-lifecycle stale

I think this is covered for medium/lows by @cji's policy update, but we should still revise the timelines for high/critical issues
