### ISSUE TITLE
Tracking Issue for Third-party Security Audit Findings and Resulting Issues

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/security#46]
I would like to have all issues filed as a result of the [Third-party Security Audit Report](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf) all link back to a single issue to make it easier to track status. I'd like to keep this issue open until we feel that all raised issues have been satisfactorily addressed.

**Comment by micahhausler** [comment]
Linkfix: [Kubernetes Final Report.pdf](https://github.com/kubernetes/community/raw/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf)

**Comment by joelsmith** [comment]
Thanks for the corrected link.
/close
Closing in favor of https://github.com/kubernetes/kubernetes/issues/81146
