### ISSUE TITLE
private-distributors-list: add Loodse

### ISSUE THREAD

**Issue by scheeles** [kubernetes/security#48]
**Actively monitored security email alias for our project:** security@loodse.com

**1. Be an actively maintained and CNCF certified distribution of Kubernetes components.**
Yes, we have Kubermatic and KubeOne https://github.com/kubermatic/kubeone
**2. Have a user base not limited to your own organization.**
KubeOne is open source and kubermatic is used by several enterprises e.g. https://metakube.syseleven.de
**3. Have a publicly verifiable track record up to present day of fixing security issues.**
We are working on upstream patches for https://github.com/kubernetes/dashboard
Additional we have an security newsletter where we announce all upstream patches   https://www.loodse.com/newsletter/
**4. Not be a downstream or rebuild of another distribution.**
This does not apply, Kubermatic and KubeOne are unique.
**5. Be a participant and active contributor in the community.**
We have several member who are working on upstream project e.g.
https://github.com/nikhita
https://github.com/maciaszczykm
https://github.com/floreks
https://github.com/alvaroaleman
**6. Accept the Embargo Policy.**
 
We accept it
**7. Be willing to contribute back.**

We are definitely willing to help!
**8. Have someone already on the list vouch for the person requesting membership on behalf of your distribution.**
Brandon Philips

**Comment by philips** [comment]
This looks fine. Approved.

@swamymsft can you format this into a PR against https://github.com/kubernetes/security/blob/master/private-distributors-list.md

**Comment by swamymsft** [comment]
> This looks fine. Approved.
> 
> @swamymsft can you format this into a PR against https://github.com/kubernetes/security/blob/master/private-distributors-list.md

Sure, I will get this done

**Comment by tallclair** [comment]
Fixed by https://github.com/kubernetes/security/pull/50
