### ISSUE TITLE
Offboard Jonathan Pulsifer

### ISSUE THREAD

**Issue by jonpulsifer** [kubernetes/security#75]
Hey folks, I was going to send an email to the team but this solves the same problem 😄

I haven't been available for a number of reasons, and, despite that I keep thinking to myself "I'll get to it later".. later never comes.

I had the chance to catch up with @tallclair in Seattle before travel was restricted and, given that, I'd like to ask that I be offboarded from the PSC, I think the position can better be filled by someone in the community.

Pardon my absenteeism, and thanks for the opportunity friends <3

**Comment by tallclair** [comment]
Thanks Jonathan. I made most of the changes as part of https://github.com/kubernetes/security/pull/70
