### ISSUE TITLE
SECURITY_CONTACTS files in all Kubernetes project repos have old link

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/security#8]
Now that the new Product Security Committee has superseded the Product Security Team, and now that documents have been moved from https://github.com/kubernetes/sig-release to this repo, all of the `SECURITY_CONTACTS` files across all other Kubernetes project repositories need to be updated. They contain a link to the old location and reference the old PST. I will open PRs across the other repositories, but I need an issue to track all of those open PRs.

More information about the creation of the Product Security Committee and the docs move:

Create the Product Security Committee: https://github.com/kubernetes/steering/issues/89
Create Product Security Committee, update references from PST to PSC: https://github.com/kubernetes/community/pull/3311
Copy docs from sig-release, rename PST to PSC: https://github.com/kubernetes/security/pull/1
security: add tombstone files to redirect to new docs: https://github.com/kubernetes/sig-release/pull/537

edit: Sorry that I titled all the PRs `SECURITY_OWNERS` instead of `SECURITY_CONTACTS`. Hopefully that wasn't too confusing.

**Comment by joelsmith** [comment]
I wanted to add a note for posterity to say that all of the "Closed" PRs were for repos that got the change via k/k's staging area changes in https://github.com/kubernetes/kubernetes/pull/75201. Once that merged, I verified that the changes made into those repos then closed their PRs.

Thanks to everyone who helped get these all merged, especially @nikhita and @spiffxp who helped shepherd the stragglers along.

We're down to https://github.com/kubernetes/cloud-provider-aws/pull/34 which is failing CI, probably because of a PR that merged ahead of it. I'll close this issue as soon as that final PR is able to merge.

**Comment by nikhita** [comment]
The last outstanding PR has merged https://github.com/kubernetes/cloud-provider-aws/pull/34

/close
