### ISSUE TITLE
Master Issue: Repo SECURITY_CONTACTS should list repo-specific contact people, not PSC members.

### ISSUE THREAD

**Issue by joelsmith** [kubernetes/security#92]
Many repositories in Kubernetes do not have repository-specific security contacts listed in their [`SECURITY_CONTACTS`](/SECURITY_CONTACTS) file. Instead, they list the PSC members (current or former). With the exception of k/k, and this repo, the list should not contain only PSC members. I'll update issues or PRs (in the case where the repo has added contacts, but has not removed the PSC) with links back to this master issue.

**Comment by sftim** [comment]
/sig security
?
